# -*- coding: utf-8 -*-
"""testcode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ELMAyrD6k0IUvWpukOwMIqAtO-9yjlM
"""

a=1
b=2
c= a+b
print (c)